// PriyoChat themes

export const THEMES = {
  ClassicBlue: {
    name: 'Classic Blue',
    isLight: true,
    darkVariant: 'DarkNeon',
    background: '#FFFFFF',
    headerBg: '#0084FF',
    headerText: '#FFFFFF',
    sentBubble: '#0084FF',
    sentText: '#FFFFFF',
    receivedBubble: '#F0F0F0',
    receivedText: '#1C1C1C',
    inputBg: '#F5F5F5',
    inputText: '#1C1C1C',
    placeholderText: '#999999',
    timestampColor: '#888888',
    gradient: ['#0084FF', '#00C6FF'],
    preview: '#0084FF',
  },

  DarkNeon: {
    name: 'Dark Neon',
    isLight: false,
    lightVariant: 'ClassicBlue',
    background: '#0D0D0D',
    headerBg: '#111111',
    headerText: '#00FFD1',
    sentBubble: '#7C00FF',
    sentText: '#FFFFFF',
    receivedBubble: '#1A1A2E',
    receivedText: '#00FFD1',
    inputBg: '#1A1A2E',
    inputText: '#FFFFFF',
    placeholderText: '#555577',
    timestampColor: '#444466',
    gradient: ['#7C00FF', '#00FFD1'],
    preview: '#7C00FF',
  },

  SoftPurple: {
    name: 'Soft Purple',
    isLight: true,
    darkVariant: 'DarkNeon',
    background: '#FAF0FF',
    headerBg: '#A855F7',
    headerText: '#FFFFFF',
    sentBubble: '#A855F7',
    sentText: '#FFFFFF',
    receivedBubble: '#EDE9FE',
    receivedText: '#4A1D96',
    inputBg: '#F3E8FF',
    inputText: '#4A1D96',
    placeholderText: '#C084FC',
    timestampColor: '#9B6DD1',
    gradient: ['#A855F7', '#EC4899'],
    preview: '#A855F7',
  },

  MinimalWhite: {
    name: 'Minimal White',
    isLight: true,
    darkVariant: 'OceanGlass',
    background: '#FFFFFF',
    headerBg: '#FFFFFF',
    headerText: '#1C1C1C',
    sentBubble: '#1C1C1C',
    sentText: '#FFFFFF',
    receivedBubble: '#EEEEEE',
    receivedText: '#1C1C1C',
    inputBg: '#F5F5F5',
    inputText: '#1C1C1C',
    placeholderText: '#AAAAAA',
    timestampColor: '#AAAAAA',
    gradient: ['#E0E0E0', '#FFFFFF'],
    preview: '#1C1C1C',
  },

  OceanGlass: {
    name: 'Ocean Glass',
    isLight: false,
    lightVariant: 'MinimalWhite',
    background: '#0A1628',
    headerBg: 'rgba(0,100,200,0.3)',
    headerText: '#FFFFFF',
    sentBubble: 'rgba(0,150,255,0.7)',
    sentText: '#FFFFFF',
    receivedBubble: 'rgba(255,255,255,0.1)',
    receivedText: '#E0F0FF',
    inputBg: 'rgba(255,255,255,0.08)',
    inputText: '#FFFFFF',
    placeholderText: 'rgba(255,255,255,0.4)',
    timestampColor: 'rgba(255,255,255,0.4)',
    gradient: ['#0A1628', '#0D3B6E'],
    preview: '#0096FF',
  },

  DoodleLight: {
    name: 'Doodle Light',
    isLight: true,
    darkVariant: 'DoodleDark',
    background: '#E5DDD5',
    bgImage: require('../../assets/patterns/doodle_light.jpg'),
    headerBg: '#075E54',
    headerText: '#FFFFFF',
    sentBubble: '#DCF8C6',
    sentText: '#1C1C1C',
    receivedBubble: '#FFFFFF',
    receivedText: '#1C1C1C',
    inputBg: '#F0F0F0',
    inputText: '#1C1C1C',
    placeholderText: '#999999',
    timestampColor: '#888888',
    gradient: ['#075E54', '#128C7E'],
    preview: '#25D366',
  },

  DoodleDark: {
    name: 'Doodle Dark',
    isLight: false,
    lightVariant: 'DoodleLight',
    background: '#0B141A',
    bgImage: require('../../assets/patterns/doodle_dark.jpg'),
    headerBg: '#1F2C34',
    headerText: '#E9EDEF',
    sentBubble: '#005C4B',
    sentText: '#E9EDEF',
    receivedBubble: '#202C33',
    receivedText: '#E9EDEF',
    inputBg: '#2A3942',
    inputText: '#E9EDEF',
    placeholderText: '#8696A0',
    timestampColor: '#8696A0',
    gradient: ['#1F2C34', '#005C4B'],
    preview: '#00A884',
  },

  WatercolorLight: {
    name: 'Watercolor',
    isLight: true,
    darkVariant: 'OilPainting',
    background: '#FDFBF7',
    bgImage: require('../../assets/patterns/watercolor_light.jpg'),
    headerBg: '#FFB6C1',
    headerText: '#1C1C1C',
    sentBubble: '#FFB6C1',
    sentText: '#1C1C1C',
    receivedBubble: '#FFFFFF',
    receivedText: '#1C1C1C',
    inputBg: '#F9F9F9',
    inputText: '#1C1C1C',
    placeholderText: '#999999',
    timestampColor: '#888888',
    gradient: ['#FFB6C1', '#FFD1DC'],
    preview: '#FFB6C1',
  },

  OilPainting: {
    name: 'Oil Painting',
    isLight: false,
    lightVariant: 'WatercolorLight',
    background: '#1A1C29',
    bgImage: require('../../assets/patterns/oil_painting.jpg'),
    headerBg: '#2A2D43',
    headerText: '#FFFFFF',
    sentBubble: '#434C75',
    sentText: '#FFFFFF',
    receivedBubble: '#2A2D43',
    receivedText: '#FFFFFF',
    inputBg: '#202235',
    inputText: '#FFFFFF',
    placeholderText: '#8696A0',
    timestampColor: '#8696A0',
    gradient: ['#1A1C29', '#2A2D43'],
    preview: '#434C75',
  },

  AbstractArt: {
    name: 'Neon Graffiti',
    isLight: false,
    lightVariant: 'SketchArt',
    background: '#0E0015',
    headerBg: '#1A0028',
    headerText: '#FF2EF7',
    sentBubble: '#FF2EF7',
    sentText: '#FFFFFF',
    receivedBubble: '#1C002E',
    receivedText: '#00FFCC',
    inputBg: '#1A0028',
    inputText: '#FFFFFF',
    placeholderText: '#8844AA',
    timestampColor: '#7733AA',
    gradient: ['#FF2EF7', '#7B00FF'],
    preview: '#FF2EF7',
  },

  SketchArt: {
    name: 'Canvas Warm',
    isLight: true,
    darkVariant: 'AbstractArt',
    background: '#FDF6EC',
    bgImage: require('../../assets/patterns/watercolor_light.jpg'),
    headerBg: '#C2714F',
    headerText: '#FFFFFF',
    sentBubble: '#C2714F',
    sentText: '#FFFFFF',
    receivedBubble: '#FFF8F0',
    receivedText: '#3D2010',
    inputBg: '#F5EDE0',
    inputText: '#3D2010',
    placeholderText: '#B08060',
    timestampColor: '#C09070',
    gradient: ['#C2714F', '#E8956A'],
    preview: '#C2714F',
  },
};

export const DEFAULT_THEME = 'DoodleLight';
